services:
  codeserver-ms:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - aggk4gggs80wos0gw4g4ckkc_kelvin-documentation:/kelvin
      - kelvin-vscode-ms-config:/home/vscode/.vscode
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - traefik.http.middlewares.authelia@file

volumes:
  kelvin-vscode-ms-config:
  aggk4gggs80wos0gw4g4ckkc_kelvin-documentation:
    external: true
