services:
  codeserver-ms:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - kelvin-documentation-ms:/kelvin
      - kelvin-vscode-ms-home:/home/abc
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:23888/"]
      interval: 30s
      timeout: 5s
      retries: 3
    labels:
      - traefik.http.middlewares.authelia@file

volumes:
  kelvin-documentation-ms:
  kelvin-vscode-ms-home:

